### PR TITLE
Fullscreen button

### PR DESCRIPTION
**Pull request by coreycla-dev**
Adds fullscreen functionality / improves aesthetics and button positioning

### CODE REVIEW

**Comment by helpimtrappedinawebserver** [comment]
Thanks for the pull request! I ran into some JS errors when trying out the new fullscreen button, but I think they can be worked out. Let's set up a time to go over this together on Discord soon, and we revise the branch to get this PR in good shape.

**Comment by coreycla-dev** [comment]
It looks like I pushed the wrong JS file. My apologies on that one. I'll submit a new pull request with the correct one here in a few minutes.

**Comment by coreycla-dev** [comment]
Sounds good! I'm available this coming Friday night, or Sunday. Do either of those work for you?

**Comment by coreycla-dev** [comment]
I realized that I neglected our lesser browsers on that last push, so I added compatibility with Firefox and IE. Nothing earth-shattering, but worth merging.

**Pull request merged**
